create database student;
use student;
create table uaa(name varchar(100),address  varchar(100));
insert into uaa(name,address)values('ganesh','ongole');
insert into uaa(name,address)values('ramesh','guntur');
insert into uaa(name,address)values('pardhu','kadpae');
show databases;
show tables;
select name from uaa;
select *from uaa;
select *from uaa where name='pardhu' and name='ganesh';
select *from uaa where name='pardhu' or name='ganesh';
select *from uaa order by name;
select *from uaa order by name desc;
select name from uaa where name=null;
select name from uaa where name is not null;
-- update uaa  set name='prasana' where name='ganesh';
alter table uaa add salary int;
insert into uaa(salary) values (12);
insert into uaa(salary) values (13);
update uaa set name='prasana' where salary='12';
delete from uaa where name='pardhu';
show tables;
delete from uaa where salary='13';
insert into uaa(salary) values (9);
insert into uaa(salary) values (15);
insert into uaa(salary) values (16);
select min(salary) from uaa;
select sum(salary from uaa;
select max(salary) from uaa;
select count(salary) from uaa;
select avg(salary) from uaa;
select *from uaa where address like '_____r';
select *from uaa where address in ('guntur','kadapa');
select *from uaa where salary BETWEEN'10' and '14';
select salary as job,name as pfolio from uaa;
create table new(name varchar(100),venue  varchar(100));
insert into new(name,venue) values('challa','bhimavaram');
show tables;
create table kotha(scamers varchar(100),cases  varchar(100));
insert into kotha(cases) values (9);
insert into kotha(cases) values (1);
insert into kotha(cases) values (6);
insert into kotha(scamers) values ('ravi');
insert into kotha(scamers) values ('johny');
insert into kotha(scamers) values ('balu');
create table kot(women varchar(100),men  varchar(100));
insert into kot(men) values ('sidhu');
insert into kot(men) values ('nandha');
insert into kot(men) values ('rambabu');
insert into kot(women) values ('srilu');
insert into kot(women) values ('pinky');
insert into kot(women) values ('jahnavi');
show tables;
select cases from kotha;
select women  from kot innner join kotha  on kot.women=kotha.cases;
select cases from kotha union  from kot;
create table munna(malli varchar(100),vardha  varchar(100));
insert into munna(malli) values ('ravvi');
select cases from kotha  union select  malli from munna;
select malli from munna where exists(
