create database jhonny;
use jhonny;
create table munna( id varchar(200),malli varchar(100),vardha  varchar(100));
insert into munna(malli) values (1);
insert into munna(malli) values (2);
insert into munna(malli) values (3);
insert into munna(vardha) values ('bunny');
insert into munna(vardha) values ('mirchi');
insert into munna(vardha) values ('don');
create table billa(id varchar(100),ganster varchar(100));
insert into billa(id) values (1);
insert into billa(id) values (2);
insert into billa(ganster) values ('usa');
insert into billa(ganster) values ('bankock');
insert into munna(id) values (2);
select malli from munna innner join id on malli.munna=billa.id;
create table puppy( id varchar(200));
select id from puppy innner join id on id.puppy=billa.id;
drop database database_name;
drop table table_name;
create table kargle( id varchar(200),malli varchar(100));
alter table kargle add jemmy varchar(200);
select *from kargle;
alter table kargle modify jemmy varchar(200) not null;
create table jolly(id varchar(100) not null,ganster varchar(100), primary key(id));
create table dolly(id varchar(100) not null,ganster varchar(100), primary key(id));
select *from dolly;
create table polly(id varchar(100) check(id>=18),ganster varchar(100), primary key(id));
